default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234
  host: localhost
  pool: 5

development:
  <<: *default
  database: connect_hub_development

test:
  <<: *default
  database: connect_hub_test

production:
  <<: *default
  database: connect_hub_production
